/**
 * Wisdom cards: one idea each, in words a curious 12-year-old could follow, with a tiny "look for yourself".
 *
 * kind "said": the teacher's actual words from a public-domain source (shown in quotation marks).
 * kind "idea": a plain-language reframe in the spirit of the teacher (never shown as a quotation).
 * The guide may only cite these cards, so it never invents quotes.
 */
export type Theme = "thoughts" | "self" | "now" | "stories" | "body" | "nature" | "stillness" | "fear" | "love" | "desire" | "play";

export interface Wisdom { id: string; teacher: string; kind: "said" | "idea"; text: string; source?: string; look: string; themes: Theme[] }

export const WISDOM: Wisdom[] = [
  { id: "jesus-truth", teacher: "Jesus", kind: "said", source: "John 8:32 (KJV)", text: "Ye shall know the truth, and the truth shall make you free.", look: "Think of one thing you believe about yourself. Is it really true, or just something you got used to?", themes: ["stories", "self"] },
  { id: "jesus-within", teacher: "Jesus", kind: "said", source: "Luke 17:21 (KJV)", text: "The kingdom of God is within you.", look: "Close your eyes. Is there a quiet place inside that's always been there, even on bad days?", themes: ["self", "stillness"] },
  { id: "jesus-lilies", teacher: "Jesus", kind: "said", source: "Matthew 6:28 (KJV)", text: "Consider the lilies of the field, how they grow; they toil not, neither do they spin.", look: "Find a flower or a plant. Is it trying hard to grow? What would it be like to grow like that?", themes: ["nature", "fear"] },
  { id: "jesus-children", teacher: "Jesus", kind: "idea", text: "Unless you become like little children, you'll miss what matters. Curious, open, not pretending to know.", look: "Look at something ordinary (a spoon, your hand) as if you've never seen one before.", themes: ["play", "now"] },
  { id: "buddha-hatred", teacher: "Buddha", kind: "said", source: "Dhammapada 5 (Müller, 1881)", text: "Hatred does not cease by hatred at any time: hatred ceases by love, this is an old rule.", look: "Think of someone who annoys you. What happens in your chest when you wish them one good thing?", themes: ["love"] },
  { id: "buddha-mind", teacher: "Buddha", kind: "idea", text: "Your mind paints the world before you see it. Change the painter, and the picture changes.", look: "Notice one mood you're in. How is it colouring what you see around you right now?", themes: ["thoughts", "stories"] },
  { id: "buddha-arrow", teacher: "Buddha", kind: "idea", text: "Pain is the first arrow. The story we tell about the pain is the second arrow, and that one we shoot ourselves.", look: "Next time something hurts, notice: what's the hurt, and what's the story about the hurt?", themes: ["stories", "body"] },
  { id: "buddha-change", teacher: "Buddha", kind: "idea", text: "Everything changes: clouds, moods, you. Holding on tight to what's always moving is what makes us suffer.", look: "Watch a cloud, a candle or your breath for a minute. Does anything stay exactly the same?", themes: ["now", "nature"] },
  { id: "ramana-who", teacher: "Sri Ramana Maharshi", kind: "idea", text: "Every time a thought comes, ask: to whom did this thought come? To me. And who am I? Then look, quietly, for the one who's asking.", look: "Ask \"Who am I?\" and don't answer with words. Just look. What do you find?", themes: ["self", "thoughts"] },
  { id: "ramana-silence", teacher: "Sri Ramana Maharshi", kind: "idea", text: "Silence isn't empty. It's the most powerful teaching there is.", look: "Sit in silence for one minute. Is silence nothing, or is it something?", themes: ["stillness"] },
  { id: "nisargadatta-love", teacher: "Sri Nisargadatta Maharaj", kind: "idea", text: "Love sees that you are everything. Wisdom sees that you are none of your labels. Life flows between the two.", look: "Which feels truer today: that you're part of everything, or that you're not any of your labels?", themes: ["self", "love"] },
  { id: "nisargadatta-iam", teacher: "Sri Nisargadatta Maharaj", kind: "idea", text: "Before any name, any job, any story, there's the simple feeling \"I am\". Stay with that, and the rest gets lighter.", look: "Feel the plain sense of being here, before your name. Is it nervous, or is it just here?", themes: ["self", "stillness"] },
  { id: "daikaku-sit", teacher: "Daikaku", kind: "idea", text: "Zen teachers like Daikaku taught that sitting isn't a way to get somewhere else. Just sitting, fully, is already the point.", look: "Sit for three minutes without trying to get anything from it. What's that like?", themes: ["stillness", "now"] },
  { id: "zen-cup", teacher: "Zen story", kind: "idea", text: "A student asked a master to teach him. The master kept pouring tea until the cup overflowed: \"You're like this cup, already full. Empty it first.\"", look: "What's one thing you're sure you already know? Can you put it down for a moment and look fresh?", themes: ["thoughts", "play"] },
  { id: "tolle-watch", teacher: "Eckhart Tolle", kind: "idea", text: "You're not the voice in your head. You're the one who hears it.", look: "Listen to your thoughts like you'd listen to a radio in another room. Who's listening?", themes: ["thoughts", "self"] },
  { id: "tolle-now", teacher: "Eckhart Tolle", kind: "idea", text: "Problems mostly live in the past and the future. Right now, in this exact moment, is there actually a problem?", look: "Check right now, this second: is anything actually wrong, or is the mind visiting tomorrow?", themes: ["now", "fear"] },
  { id: "krishnamurti-observe", teacher: "Krishnamurti", kind: "idea", text: "Watching without judging, without calling things good or bad, is a kind of intelligence most people never use.", look: "Look out a window for one minute without labelling anything good or bad.", themes: ["thoughts", "nature"] },
  { id: "krishnamurti-no-guru", teacher: "Krishnamurti", kind: "idea", text: "Truth is a pathless land. No teacher can walk it for you, not even this app.", look: "What's something you've discovered for yourself, that nobody told you?", themes: ["self", "play"] },
  { id: "osho-celebrate", teacher: "Osho", kind: "idea", text: "Life isn't a problem to solve. It's a mystery to enjoy. Dance a little.", look: "Put on a song and move however your body wants for one minute. Who were you while dancing?", themes: ["play", "body"] },
  { id: "osho-witness", teacher: "Osho", kind: "idea", text: "Be a witness, like someone sitting on a riverbank watching boats go by. Thoughts are boats. You don't have to jump on each one.", look: "Name your thoughts as they float by: \"boat… boat… boat\". Do you have to get on?", themes: ["thoughts", "stillness"] },
  { id: "bashar-excitement", teacher: "Bashar", kind: "idea", text: "Excitement is a compass. Follow the most exciting thing you can do right now, and let go of how it turns out.", look: "What's the most exciting small thing you could do today? Could you do it without needing it to go perfectly?", themes: ["desire", "play"] },
  { id: "bashar-mirror", teacher: "Bashar", kind: "idea", text: "The world is like a mirror. It can't smile first. Change the face, and the reflection follows.", look: "Notice one belief you have about people. Where do you see it reflected back?", themes: ["stories"] },
  { id: "neville-feel", teacher: "Neville Goddard", kind: "idea", text: "Imagine the wish already came true, and feel it from the inside, like a memory. Imagination is where things start.", look: "Picture a tiny scene that would happen if your wish were already true. How does your body feel in it?", themes: ["desire"] },
  { id: "transurfing-importance", teacher: "Transurfing", kind: "idea", text: "When something feels super important, you grip it, and gripping makes things harder. Want it, but hold it lightly.", look: "Pick something that feels huge. Say: \"It'd be nice, and I'll be okay either way.\" What changes?", themes: ["desire", "fear"] },
  { id: "transurfing-pendulum", teacher: "Transurfing", kind: "idea", text: "Some things (drama, arguments, endless scrolling) feed on your attention. You can just… not feed them.", look: "Notice one thing today that's pulling hard for your attention. What happens if you smile and let it go?", themes: ["thoughts"] },
  { id: "crone-without", teacher: "Peter Crone", kind: "idea", text: "Most of our limits are just old ideas about ourselves we never checked. The cage was never locked.", look: "Finish the sentence \"I'm the kind of person who can't…\". Then ask: who would I be without that?", themes: ["stories", "self"] },
  { id: "dispenza-habit", teacher: "Joe Dispenza", kind: "idea", text: "Your brain is like a path in the grass: the more you walk it, the deeper it gets. You can start walking a new one any day.", look: "What's one thought you think every morning? What new one would you like to practise instead?", themes: ["thoughts", "body"] },
  { id: "science-breath", teacher: "Neuroscience", kind: "idea", text: "Breathing out longer than you breathe in tells your body it's safe. It's a remote control for calm you always carry.", look: "Breathe in for 4, out for 6, five times. Notice what your shoulders do.", themes: ["body", "fear"] },
  { id: "science-predict", teacher: "Neuroscience", kind: "idea", text: "Your brain is a prediction machine. It mostly shows you what it expects, not what's there. Curiosity updates the map.", look: "Walk somewhere familiar and spot three things you've never noticed before.", themes: ["thoughts", "nature"] },
  { id: "laotzu-nature", teacher: "Lao Tzu", kind: "idea", text: "Nature doesn't hurry, yet everything gets done.", look: "Watch something slow (a plant, the tide, the sky). What would today feel like at nature's pace?", themes: ["nature", "now"] },

  // Zen & Tao
  { id: "daikaku-everyday", teacher: "Daikaku", kind: "idea", text: "Daikaku taught samurai who had no time to live in a temple. Zen isn't only on the cushion, he said: bring the same clear mind to walking, standing, eating and work.", look: "Do one ordinary thing today (tying shoes, pouring water) as if it were your meditation.", themes: ["now", "stillness"] },
  { id: "daikaku-see", teacher: "Daikaku", kind: "idea", text: "Reading about Zen is like reading a menu. Daikaku kept pointing his students back to the meal: see your own nature for yourself.", look: "Put this card down and taste the next sip of water as if it were the first ever.", themes: ["self", "now"] },
  { id: "bukko-dont-worry", teacher: "Bukkō", kind: "idea", text: "Before a huge invasion, Bukkō gave the young ruler Tokimune a note with three characters on it: \"Don't worry.\" Worry never fought a single battle.", look: "Name one worry. Now ask: is worrying doing anything useful for it right this second?", themes: ["fear", "thoughts"] },
  { id: "bukko-lightning", teacher: "Bukkō", kind: "idea", text: "When soldiers held a sword to Bukkō's neck, he calmly recited a poem: their sword would be like lightning cutting through the spring breeze. You can't cut the breeze.", look: "When fear shows up, feel for the part of you that's like air, the part nothing can cut.", themes: ["fear", "self"] },
  { id: "bukko-katsu", teacher: "Bukkō", kind: "idea", text: "Bukkō told his samurai student to meet fear head on, like a lion, instead of thinking about it in circles. Thinking about fear feeds it; meeting it shrinks it.", look: "Pick one small thing you've been avoiding. Do the first tiny step now, before the thinking starts.", themes: ["fear", "body"] },
  { id: "bodhidharma-mind", teacher: "Bodhidharma", kind: "idea", text: "A student begged Bodhidharma: \"My mind isn't at peace. Please calm it.\" \"Bring me your mind and I'll calm it.\" The student searched and searched: \"I can't find it.\" \"There. I've calmed it.\"", look: "Try to find your mind. Not a thought: the mind itself. Where is it?", themes: ["self", "thoughts"] },
  { id: "bodhidharma-wall", teacher: "Bodhidharma", kind: "idea", text: "Bodhidharma's whole teaching fit on a napkin: don't depend on words, point straight at your own mind, see what you really are.", look: "Without using any words in your head, notice that you're here.", themes: ["self", "stillness"] },
  { id: "huineng-mirror", teacher: "Hui Neng", kind: "idea", text: "One monk said the mind is a mirror you must keep wiping clean. Hui Neng, a kitchen helper, answered: there's no mirror and no dust. What you really are was never dirty.", look: "Think of something you feel bad about. Is the awareness that notices it dirty too?", themes: ["self", "stories"] },
  { id: "sosan-preferences", teacher: "Sosan", kind: "idea", text: "The Great Way isn't hard, said Sosan, for people who don't keep picking and choosing. Most of our upset is just \"I like this, I don't like that\".", look: "For the next minute, let every sound be fine, even the annoying ones. What happens?", themes: ["desire", "now"] },
  { id: "dogen-forget", teacher: "Dōgen", kind: "idea", text: "To study the Way is to study the self. To study the self is to forget the self. And when you forget yourself, the whole world comes to meet you.", look: "Get so into a song, a game or a drawing that you forget yourself. Who was there?", themes: ["self", "play"] },
  { id: "hakuin-hand", teacher: "Hakuin", kind: "idea", text: "You know the sound of two hands clapping. Hakuin asked: what is the sound of one hand? It's not a riddle to solve. It's a door to the quiet that's always here.", look: "Hold up one hand and listen. What do you hear?", themes: ["stillness", "play"] },
  { id: "hakuin-isthatso", teacher: "Hakuin", kind: "idea", text: "Villagers blamed Hakuin for something he didn't do. He just said \"Is that so?\" When they found out the truth and apologised, he said again: \"Is that so?\"", look: "When someone praises or blames you today, try a quiet \"Is that so?\" inside.", themes: ["stories", "self"] },
  { id: "ikkyu-pause", teacher: "Ikkyū", kind: "idea", text: "Ikkyū's name means \"one pause\". Between where you've been and where you're going, he said, take a little rest. Life is that rest.", look: "Stop for one full breath right now. Nothing to do. That's an Ikkyū pause.", themes: ["now", "stillness"] },
  { id: "basho-frog", teacher: "Bashō", kind: "idea", text: "An old pond. A frog jumps in. The sound of water. Bashō's most famous poem is about one splash, noticed completely.", look: "Listen for one small sound today and hear it completely, like it's the only sound in the world.", themes: ["now", "nature"] },
  { id: "ryokan-moon", teacher: "Ryōkan", kind: "idea", text: "A thief broke into Ryōkan's hut and found nothing to take, so Ryōkan gave him his clothes. Later, sitting under the night sky, he smiled: the thief left the most beautiful thing behind, the moon at the window.", look: "What's something wonderful that nobody can take from you?", themes: ["desire", "nature"] },
  { id: "zen-chop-wood", teacher: "Zen story", kind: "idea", text: "Before awakening: chop wood, carry water. After awakening: chop wood, carry water. Nothing changes, and everything does.", look: "Do one chore today with your full attention. Is it still boring?", themes: ["now", "play"] },
  { id: "zen-finger-moon", teacher: "Zen story", kind: "idea", text: "A teaching is a finger pointing at the moon. Don't stare at the finger. Look where it's pointing.", look: "Which card in this deck are you holding on to? Where is it pointing you?", themes: ["thoughts", "self"] },
  { id: "suzuki-beginner", teacher: "Shunryu Suzuki", kind: "idea", text: "In a beginner's mind there are many possibilities. In an expert's mind there are few. Stay a beginner.", look: "Pick something you're sure you know well. Look at it like a total beginner.", themes: ["play", "thoughts"] },
  { id: "thich-dishes", teacher: "Thich Nhat Hanh", kind: "idea", text: "Wash the dishes to wash the dishes, not to get them done. Hurrying through life to get to the good part means missing life.", look: "Next time you wash something, feel the water temperature, the soap, the weight of the cup.", themes: ["now", "body"] },
  { id: "thich-breath", teacher: "Thich Nhat Hanh", kind: "idea", text: "Breathing in, I calm my body. Breathing out, I smile. Your breath is a friend that's been with you every second of your life.", look: "Say those two lines silently with three breaths. Did a smile sneak in?", themes: ["body", "stillness"] },

  // The Buddha's way
  { id: "buddha-raft", teacher: "Buddha", kind: "idea", text: "The Buddha said his teaching is like a raft. Use it to cross the river, then put it down. Don't carry the raft on your head for the rest of your life.", look: "Is there a rule or belief that helped you once but now just feels heavy?", themes: ["stories", "thoughts"] },
  { id: "buddha-light", teacher: "Buddha", kind: "idea", text: "Don't believe something just because a teacher said it, or because a book says it, or because everyone believes it. Test it in your own life.", look: "Pick one card in this deck and test it today. Did it hold up?", themes: ["self", "play"] },
  { id: "tilopa-rest", teacher: "Tilopa", kind: "idea", text: "Tilopa's advice in six bits: don't replay the past, don't imagine the future, don't think about now, don't analyse, don't try to control. Just rest.", look: "Try Tilopa's six bits for one minute. What's left when you stop all that?", themes: ["stillness", "now"] },
  { id: "atisha-breathe", teacher: "Atisha", kind: "idea", text: "Atisha taught a brave kind of breathing: breathe in someone's sadness, breathe out kindness to them. It turns out the heart gets bigger, not heavier.", look: "Think of someone having a hard time. Breathe in their trouble, breathe out a wish for them to be okay.", themes: ["love", "body"] },
  { id: "saraha-arrow", teacher: "Saraha", kind: "idea", text: "Saraha left fancy rituals behind to live with an arrow-maker woman. Watching her work with total focus, he woke up. The sacred was in the ordinary all along.", look: "Watch someone do something they're really good at. What does full attention look like?", themes: ["now", "love"] },
  { id: "mahavira-life", teacher: "Mahavira", kind: "idea", text: "Every living thing, down to the smallest bug, wants to live and doesn't want to hurt. Mahavira built a whole path on that one simple fact.", look: "Next time you see a bug, pause and watch it for a moment before doing anything.", themes: ["love", "nature"] },
  { id: "chah-glass", teacher: "Ajahn Chah", kind: "idea", text: "Ajahn Chah loved his glass, and knew it was already broken. Because he knew it would break one day, every day he had it was a gift.", look: "Look at something you love. Can you enjoy it more knowing it won't last forever?", themes: ["love", "now"] },
  { id: "pema-sky", teacher: "Pema Chödrön", kind: "idea", text: "You are the sky. Everything else (moods, worries, bad days) is just weather.", look: "What's the weather inside you right now? Can you feel the sky it's happening in?", themes: ["self", "fear"] },
  { id: "pema-lean-in", teacher: "Pema Chödrön", kind: "idea", text: "When something feels uncomfortable, the brave move is to lean in and get curious, instead of running away.", look: "Find a small uncomfortable feeling in your body. Get curious: what shape is it? Does it move?", themes: ["fear", "body"] },

  // Sages of India
  { id: "ramana-leather", teacher: "Sri Ramana Maharshi", kind: "idea", text: "Trying to fix the whole world so it never hurts you is like trying to cover the earth with leather so you never step on a stone. Easier to wear sandals.", look: "What's one thing you keep trying to change out there that you could meet differently in here?", themes: ["stories", "fear"] },
  { id: "ramana-train", teacher: "Sri Ramana Maharshi", kind: "idea", text: "Some people sit on a train and still carry their luggage on their head. Ramana said: put it down. Life is carrying you anyway.", look: "What are you carrying today that you could put down for an hour?", themes: ["fear", "body"] },
  { id: "ramana-be", teacher: "Sri Ramana Maharshi", kind: "idea", text: "Ramana's whole teaching in three words: be as you are. Not who you should be. As you are.", look: "For one minute, stop trying to improve anything about yourself. What's that like?", themes: ["self", "stillness"] },
  { id: "nisargadatta-abyss", teacher: "Sri Nisargadatta Maharaj", kind: "idea", text: "The mind sees a huge gap between you and everyone else. The heart just walks across it.", look: "Think of someone who feels far away from you. What does your heart know that your mind doesn't?", themes: ["love", "thoughts"] },
  { id: "nisargadatta-pretend", teacher: "Sri Nisargadatta Maharaj", kind: "idea", text: "Don't pretend to be what you're not. Don't refuse to be what you are. That's most of the path, right there.", look: "Where today did you pretend a little? Where did you hide a little?", themes: ["self", "stories"] },
  { id: "nisargadatta-not-that", teacher: "Sri Nisargadatta Maharaj", kind: "idea", text: "You're not your body, your name or your thoughts: you're the one who notices them. Whatever you can watch, you're not that.", look: "Notice your hand, then your thoughts, then your mood. Can you find the one who's noticing?", themes: ["self", "thoughts"] },
  { id: "ashtavakra-free", teacher: "Ashtavakra", kind: "idea", text: "If you think you're free, you're free. If you think you're stuck, you're stuck. So much of the cage is made of thinking.", look: "Say \"I'm stuck\" and feel your body. Now say \"I'm free\". Which one is the real you?", themes: ["stories", "self"] },
  { id: "vbt-gap", teacher: "Vigyan Bhairav Tantra", kind: "idea", text: "Between breathing in and breathing out, there's a tiny pause. Shiva told his beloved: rest there, and you'll find something huge.", look: "Breathe in. Notice the little pause at the top. Breathe out. Notice the pause at the bottom.", themes: ["stillness", "body"] },
  { id: "vbt-sound", teacher: "Vigyan Bhairav Tantra", kind: "idea", text: "Listen to a sound until it fades away completely, then keep listening to where it went.", look: "Tap a glass or ring a bell (Koan's Sit bells work). Follow the sound all the way into silence.", themes: ["stillness", "now"] },
  { id: "patanjali-waves", teacher: "Patanjali", kind: "idea", text: "Yoga isn't about bendy poses. Patanjali said it's letting the waves of the mind settle, so you can see the bottom of the lake.", look: "Imagine your thoughts as ripples on a pond. Stop throwing stones for a minute. What can you see?", themes: ["thoughts", "stillness"] },
  { id: "lalla-home", teacher: "Lalla", kind: "idea", text: "Lalla searched everywhere for the divine. In the end she found it at home, inside herself, and started dancing.", look: "Put your hand on your chest. Is anything there that's been there all along?", themes: ["self", "love"] },
  { id: "mirabai-dance", teacher: "Mirabai", kind: "idea", text: "Mirabai was a princess who danced in the streets for love, even when the palace told her to stop. Love doesn't care what people think.", look: "What do you love doing so much you'd do it even if people laughed?", themes: ["love", "play"] },
  { id: "papaji-quiet", teacher: "Papaji", kind: "idea", text: "Papaji's advice was two words: keep quiet. Not just your mouth. Don't stir up the next thought, and see what's already here.", look: "Keep quiet for thirty seconds, inside too. What was there?", themes: ["stillness", "thoughts"] },
  { id: "anandamayi-joy", teacher: "Anandamayi Ma", kind: "idea", text: "Her name means \"joy-filled mother\". She said joy isn't something you earn. It's what you are when you stop getting in the way.", look: "What's getting in the way of a little joy right now? Can you set it aside for a minute?", themes: ["play", "self"] },

  // Sufis & poets
  { id: "rumi-guesthouse", teacher: "Rumi", kind: "idea", text: "Being human is like running a guest house. Joy, sadness, grumpiness: each feeling is a visitor. Welcome them all. They don't stay forever.", look: "What feeling is visiting you right now? Can you say \"welcome\" to it?", themes: ["love", "fear"] },
  { id: "rumi-ocean", teacher: "Rumi", kind: "idea", text: "You're not a drop in the ocean. You're the whole ocean in a drop.", look: "Feel your heartbeat. It's the same life beating in every creature. How big are you, really?", themes: ["self", "nature"] },
  { id: "rabia-torch", teacher: "Rabia", kind: "idea", text: "Rabia ran through the streets with a torch and a bucket of water. \"I'll burn down heaven and put out hell, so people love for love's sake, not for reward or fear.\"", look: "Do one kind thing today that nobody will ever know about.", themes: ["love", "desire"] },
  { id: "nasruddin-key", teacher: "Mulla Nasruddin", kind: "idea", text: "Nasruddin was searching under a streetlight. \"What did you lose?\" \"My key.\" \"Where did you drop it?\" \"In my house.\" \"Then why look here?\" \"There's more light here!\"", look: "Where are you looking for happiness just because it's easy to look there?", themes: ["desire", "play"] },
  { id: "nasruddin-donkey", teacher: "Mulla Nasruddin", kind: "idea", text: "Nasruddin rode through the village looking everywhere for his lost donkey. He was sitting on it.", look: "What are you looking for that you already have?", themes: ["self", "play"] },
  { id: "attar-birds", teacher: "Attar", kind: "idea", text: "Thousands of birds set out to find their king, the Simorgh. Only thirty made it. When they arrived, they saw their own reflection: \"si morgh\" means \"thirty birds\". They were what they were looking for.", look: "If what you're searching for were already you, how would today be different?", themes: ["self", "desire"] },
  { id: "baal-shem-joy", teacher: "Baal Shem Tov", kind: "idea", text: "The Baal Shem Tov taught that joy itself is a kind of prayer, and that every ordinary moment hides a spark of the sacred waiting to be noticed.", look: "Find one tiny spark of goodness in an ordinary thing in front of you.", themes: ["play", "love"] },

  // Greeks & Stoics
  { id: "socrates-know-nothing", teacher: "Socrates", kind: "idea", text: "Socrates was called the wisest man in Athens. His secret? He was the only one who knew that he didn't know.", look: "What's something you were completely sure about that turned out wrong?", themes: ["thoughts", "play"] },
  { id: "diogenes-sunlight", teacher: "Diogenes", kind: "idea", text: "The most powerful king in the world, Alexander, offered Diogenes anything he wanted. Diogenes, sunbathing, said: \"Move a bit. You're blocking my sun.\"", look: "What simple thing already makes you happy that no money could improve?", themes: ["desire", "play"] },
  { id: "pythagoras-silence", teacher: "Pythagoras", kind: "idea", text: "Pythagoras asked new students to listen in silence for years before they spoke. He knew most of learning is listening.", look: "In your next conversation, listen twice as much as you talk. What do you notice?", themes: ["stillness", "love"] },

  // Mystics of the West
  { id: "francis-brother-sun", teacher: "Francis of Assisi", kind: "idea", text: "Francis called the sun his brother and the moon his sister. He even preached to birds. Everything was family.", look: "Greet the sun, a tree or the moon today like a family member. Does anything shift?", themes: ["nature", "love"] },
  { id: "hildegard-green", teacher: "Hildegard of Bingen", kind: "idea", text: "Hildegard saw a greening power in everything alive, the same force pushing up leaves in spring and healing a cut on your knee.", look: "Find something growing. Can you feel the same greening force in your own body?", themes: ["nature", "body"] },
  { id: "gurdjieff-asleep", teacher: "Gurdjieff", kind: "idea", text: "Most people walk through life asleep, Gurdjieff said, doing everything on autopilot. Waking up starts with simply remembering yourself: \"I am here.\"", look: "Set a reminder. When it goes off, stop and say silently: \"I am here.\"", themes: ["now", "self"] },
  { id: "jung-shadow", teacher: "Carl Jung", kind: "idea", text: "What we don't look at in ourselves runs our life from the shadows, and we call it bad luck. Turn on the light, and it loses its power.", look: "What annoys you most in other people? Is there a little of that in you too?", themes: ["stories", "self"] },

  // Teachers of today
  { id: "osho-alive", teacher: "Osho", kind: "idea", text: "The real question isn't whether there's life after death. It's whether you're alive before death.", look: "What's one thing that makes you feel really, fully alive? When did you last do it?", themes: ["play", "now"] },
  { id: "osho-laugh", teacher: "Osho", kind: "idea", text: "Laughter is a meditation. When you really laugh, for a moment the thinking stops and you're totally here.", look: "Laugh for no reason for thirty seconds (fake it, it turns real). What's left afterwards?", themes: ["play", "body"] },
  { id: "osho-fear-love", teacher: "Osho", kind: "idea", text: "Don't move the way fear tells you to move. Move the way love tells you to move.", look: "Think of a choice you're facing. What would fear pick? What would love pick?", themes: ["fear", "love"] },
  { id: "osho-dynamic", teacher: "Osho", kind: "idea", text: "Modern people can't just sit still: too much is bottled up. Shake, jump, breathe hard and let it out first. Then the silence comes by itself.", look: "Shake your whole body for one minute like a wet dog. Then stand totally still. Notice.", themes: ["body", "stillness"] },
  { id: "krishnamurti-observer", teacher: "Krishnamurti", kind: "idea", text: "When you're angry, is there an angry you, separate from the anger? Or, when you really look, is there just anger?", look: "Next time a strong feeling shows up, look for the one who's having it.", themes: ["self", "thoughts"] },
  { id: "tolle-acceptance", teacher: "Eckhart Tolle", kind: "idea", text: "Whatever this moment holds, accept it as if you'd chosen it. Then act, if action is needed. Fighting what already is just adds suffering.", look: "Find one thing about right now you're resisting. Say: \"Okay, this is here.\" What softens?", themes: ["now", "fear"] },
  { id: "tolle-body", teacher: "Eckhart Tolle", kind: "idea", text: "Feel the aliveness inside your hands. That tingling is a doorway out of your head and into the now.", look: "Close your eyes. Can you feel your hands from the inside, without looking at them?", themes: ["body", "now"] },
  { id: "watts-teeth", teacher: "Alan Watts", kind: "idea", text: "Trying to define yourself is like trying to bite your own teeth.", look: "Try to see your own eyes without a mirror. Then try to know yourself the same way. Funny, isn't it?", themes: ["self", "play"] },
  { id: "watts-music", teacher: "Alan Watts", kind: "idea", text: "Life is like music. The point of a song isn't to get to the end. The point is to sing, or dance, while it's playing.", look: "What are you rushing to finish? Can you enjoy the middle of it?", themes: ["now", "play"] },
  { id: "ramdass-here", teacher: "Ram Dass", kind: "idea", text: "Be here now. Not later, when things are perfect. Here, now, as things are.", look: "Name three things you can see, two you can hear, one you can feel. That's here, now.", themes: ["now"] },
  { id: "ramdass-home", teacher: "Ram Dass", kind: "idea", text: "We're all just walking each other home.", look: "Who walked with you when things were hard? Who could you walk with today?", themes: ["love"] },
  { id: "katie-true", teacher: "Byron Katie", kind: "idea", text: "Take a thought that hurts and ask four questions. Is it true? Can I absolutely know it's true? How do I react when I believe it? Who would I be without it?", look: "Try the four questions on one thought that's bugging you today.", themes: ["stories", "thoughts"] },
  { id: "katie-reality", teacher: "Byron Katie", kind: "idea", text: "When you argue with reality, you lose, but only every time.", look: "What \"should\" be different right now? What happens if you stop arguing with it for a minute?", themes: ["stories", "now"] },
  { id: "mooji-thought", teacher: "Mooji", kind: "idea", text: "Thoughts are like people knocking at the door. You don't have to invite every one of them in for tea.", look: "When a thought knocks today, peek through the window first. Do you want this one in?", themes: ["thoughts"] },
  { id: "spira-screen", teacher: "Rupert Spira", kind: "idea", text: "Awareness is like a movie screen. Happy films, scary films: the screen is never burned by the fire or soaked by the rain.", look: "Notice what you're experiencing right now. Then notice the knowing of it, the screen.", themes: ["self", "fear"] },
  { id: "singer-roommate", teacher: "Michael Singer", kind: "idea", text: "Imagine the voice in your head was a roommate who talked nonstop. You'd never take all its advice. So why take it now?", look: "Listen to your inner roommate for a minute. Would you actually want to live with them?", themes: ["thoughts", "play"] },
  { id: "dispenza-new", teacher: "Joe Dispenza", kind: "idea", text: "If you think the same thoughts, you make the same choices, which make the same feelings, which make the same day. Change one link in the chain.", look: "Do one thing differently today: a new route, a new breakfast, a new reply. Notice how it feels.", themes: ["thoughts", "play"] },
  { id: "crone-freedom", teacher: "Peter Crone", kind: "idea", text: "Freedom isn't getting rid of a problem. It's seeing the problem was a story you never questioned.", look: "Name one problem. Now tell it as a story: \"Once upon a time, someone believed…\".", themes: ["stories"] },
  { id: "bashar-circumstance", teacher: "Bashar", kind: "idea", text: "Circumstances don't matter, only your state of being matters. The same rain is a disaster or a dance, depending on who's standing in it.", look: "Pick one annoying circumstance today. Try meeting it from a playful state. What changes?", themes: ["stories", "play"] },
  { id: "neville-assume", teacher: "Neville Goddard", kind: "idea", text: "Live in the end: assume the feeling of the wish fulfilled. What you keep feeling as true tends to shape how you live.", look: "Walk for one minute as if your wish already came true. How do you move?", themes: ["desire", "body"] },

  // Science
  { id: "science-wander", teacher: "Psychology", kind: "idea", text: "A big study found that people's minds wander almost half the time, and they're less happy when it does, even when it wanders somewhere nice.", look: "Catch your mind wandering three times today. Gently bring it back to what you're doing.", themes: ["thoughts", "now"] },
  { id: "science-name", teacher: "Neuroscience", kind: "idea", text: "Just naming a feeling (\"this is worry\") calms the brain's alarm system a little. Name it to tame it.", look: "What are you feeling right now? Name it in one or two words. Does it shift?", themes: ["fear", "body"] },
  { id: "science-wave", teacher: "Neuroscience", kind: "idea", text: "The chemical rush of an emotion passes through the body in about ninety seconds. If it lasts longer, it's usually because we keep re-telling the story.", look: "Next time a strong feeling hits, time it. Feel it fully for ninety seconds without the story.", themes: ["body", "stories"] },
  { id: "science-awe", teacher: "Psychology", kind: "idea", text: "Feeling awe (at stars, oceans, mountains, even a tiny ant) makes our worries feel smaller and makes us kinder.", look: "Find something today that makes you go \"wow\". Stay with the wow for a full minute.", themes: ["nature", "fear"] },
  { id: "science-nature", teacher: "Psychology", kind: "idea", text: "About twenty minutes in nature, even a park, lowers stress hormones. Your body knows it belongs outside.", look: "Spend twenty minutes outside today without your phone. How does your body feel afterwards?", themes: ["nature", "body"] },
  // Sufis & poets: verbatim, public domain
  { id: "blake-grain", teacher: "William Blake", kind: "said", source: "Auguries of Innocence (c. 1803)", text: "To see a World in a Grain of Sand / And a Heaven in a Wild Flower / Hold Infinity in the palm of your hand / And Eternity in an hour", look: "Look at the smallest thing near you, a crumb or a thread, for one whole minute as if it were a world.", themes: ["nature", "now"] },
  { id: "blake-doors", teacher: "William Blake", kind: "said", source: "The Marriage of Heaven and Hell (c. 1790)", text: "If the doors of perception were cleansed every thing would appear to man as it is, infinite.", look: "Look at your own hand as if you'd never seen a hand before. What do you usually skip?", themes: ["thoughts", "now"] },
  { id: "thoreau-woods", teacher: "Henry David Thoreau", kind: "said", source: "Walden (1854)", text: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.", look: "Do the next ordinary thing (a sip of water, tying a shoe) completely on purpose.", themes: ["now", "nature"] },
  { id: "thoreau-simplicity", teacher: "Henry David Thoreau", kind: "said", source: "Walden (1854)", text: "Our life is frittered away by detail. An honest man has hardly need to count more than his ten fingers, or in extreme cases he may add his ten toes, and lump the rest. Simplicity, simplicity, simplicity!", look: "Count on your fingers the things that truly matter to you today. Do you run out of fingers, or of things?", themes: ["desire", "play"] },
  { id: "thoreau-stream", teacher: "Henry David Thoreau", kind: "said", source: "Walden (1854)", text: "Time is but the stream I go a-fishing in. I drink at it; but while I drink I see the sandy bottom and detect how shallow it is.", look: "Close your eyes and look for where \"now\" ends and \"later\" begins. Can you find the edge?", themes: ["now", "nature"] },
  { id: "whitman-multitudes", teacher: "Walt Whitman", kind: "said", source: "Song of Myself 51 (1892)", text: "Do I contradict myself? / Very well then I contradict myself, / (I am large, I contain multitudes.)", look: "Notice two feelings inside you right now that don't agree. Can you let both of them stay?", themes: ["self", "play"] },
  { id: "whitman-leaf", teacher: "Walt Whitman", kind: "said", source: "Song of Myself 31 (1892)", text: "I believe a leaf of grass is no less than the journey-work of the stars,", look: "Find one leaf or blade of grass and look at it as if the whole universe worked hard to make it.", themes: ["nature"] },
  { id: "whitman-grass", teacher: "Walt Whitman", kind: "said", source: "Song of Myself 6 (1892)", text: "A child said What is the grass? fetching it to me with full hands; / How could I answer the child? I do not know what it is any more than he.", look: "Pick something you think you know, a cloud or your breath, and ask \"What is it, really?\" Stay with not knowing.", themes: ["nature", "play"] },
  { id: "gibran-children", teacher: "Kahlil Gibran", kind: "said", source: "The Prophet, On Children (1923)", text: "Your children are not your children. / They are the sons and daughters of Life’s longing for itself. / They come through you but not from you,", look: "Think of one thing about you that nobody gave you, not even your parents. Where did it come from?", themes: ["self", "love"] },
  { id: "gibran-joy", teacher: "Kahlil Gibran", kind: "said", source: "The Prophet, On Joy and Sorrow (1923)", text: "Your joy is your sorrow unmasked.", look: "Think of something that makes you happy. Can you feel the little ache of maybe losing it, hiding just behind?", themes: ["love", "fear"] },
  { id: "gibran-pain", teacher: "Kahlil Gibran", kind: "said", source: "The Prophet, On Pain (1923)", text: "Your pain is the breaking of the shell that encloses your understanding.", look: "Next time something stings, get curious: what is it trying to crack open?", themes: ["body", "fear"] },
  { id: "gibran-a-truth", teacher: "Kahlil Gibran", kind: "said", source: "The Prophet, On Self-Knowledge (1923)", text: "Say not, “I have found the truth,” but rather, “I have found a truth.”", look: "Take one thing you're sure about and start it with \"One truth I've found is…\". How does it feel?", themes: ["thoughts", "stories"] },
  { id: "emerson-trust", teacher: "Ralph Waldo Emerson", kind: "said", source: "Self-Reliance (1841)", text: "Trust thyself: every heart vibrates to that iron string.", look: "Hand on chest, ask a small question (what do I actually want for lunch?). Feel the answer before your head argues.", themes: ["self", "body"] },
  { id: "emerson-roses", teacher: "Ralph Waldo Emerson", kind: "said", source: "Self-Reliance (1841)", text: "These roses under my window make no reference to former roses or to better ones; they are for what they are; they exist with God to-day. There is no time to them.", look: "Find a plant or a pet. It isn't comparing itself to anyone. Can you try that for ten seconds?", themes: ["now", "nature"] },
  { id: "muir-mountains", teacher: "John Muir", kind: "said", source: "Our National Parks (1901)", text: "Climb the mountains and get their good tidings. Nature’s peace will flow into you as sunshine flows into trees.", look: "Step outside or to a window and let the light land on your face the way it lands on a tree.", themes: ["nature", "body"] },
  { id: "muir-home", teacher: "John Muir", kind: "said", source: "Our National Parks (1901)", text: "Thousands of tired, nerve-shaken, over-civilized people are beginning to find out that going to the mountains is going home;", look: "Find the wildest thing you can see right now, even a weed in a crack. Does some part of you feel at home?", themes: ["nature"] },
  { id: "rumi-mirror", teacher: "Rumi", kind: "said", source: "Masnavi I (Whinfield, 1887)", text: "Knowest thou why thy mirror reflects not? / Because the rust has not been scoured from its face.", look: "Notice one opinion that colours how you see someone. What do they look like with it wiped off for a moment?", themes: ["self", "thoughts"] },
  // Greeks, Stoics and the West: verbatim, public domain
  { id: "heraclitus-river", teacher: "Heraclitus", kind: "said", source: "Fragment 41 (Burnet, 1892)", text: "You cannot step twice into the same rivers; for fresh waters are ever flowing in upon you.", look: "Is the \"you\" who started reading this card exactly the same you reading this word?", themes: ["now", "self", "nature"] },
  { id: "heraclitus-sun", teacher: "Heraclitus", kind: "said", source: "Fragment 32 (Burnet, 1892)", text: "The sun is new every day.", look: "Look out a window as if you'd never seen today's light before, because you haven't.", themes: ["now", "nature"] },
  { id: "heraclitus-sought", teacher: "Heraclitus", kind: "said", source: "Fragment 80 (Burnet, 1892)", text: "I have sought for myself.", look: "Go looking for \"me\" right now. In your head? Your chest? Your name? What do you actually find?", themes: ["self"] },
  { id: "heraclitus-soul", teacher: "Heraclitus", kind: "said", source: "Fragment 71 (Burnet, 1892)", text: "You will not find the boundaries of soul by travelling in any direction, so deep is the measure of it.", look: "Close your eyes and feel for the edge of your awareness. Where does it stop?", themes: ["self", "stillness"] },
  { id: "heraclitus-child", teacher: "Heraclitus", kind: "said", source: "Fragment 79 (Burnet, 1892)", text: "Time is a child playing draughts, the kingly power is a child's.", look: "Picture today as a game a kid is playing. Which piece just moved?", themes: ["play", "now"] },
  { id: "socrates-unexamined", teacher: "Socrates", kind: "said", source: "Plato, Apology (Jowett)", text: "…the unexamined life is not worth living", look: "Pick one thing you did today on autopilot and ask it \"why?\" three times.", themes: ["thoughts", "stories"] },
  { id: "socrates-know", teacher: "Socrates", kind: "said", source: "Plato, Apology (Jowett)", text: "I neither know nor think that I know.", look: "Hold one thing you're sure about as \"I don't actually know\" for ten seconds. What opens up?", themes: ["thoughts", "play"] },
  { id: "epictetus-views", teacher: "Epictetus", kind: "said", source: "Enchiridion V (Higginson, 1865)", text: "Men are disturbed not by things, but by the views which they take of things.", look: "Think of something that bugs you. Split it into \"what happened\" and \"what I'm telling myself about it\".", themes: ["thoughts", "stories", "fear"] },
  { id: "epictetus-power", teacher: "Epictetus", kind: "said", source: "Enchiridion I (Higginson, 1865)", text: "There are things which are within our power, and there are things which are beyond our power.", look: "Make two quick piles in your head: what you can change in the next minute, and what you can't.", themes: ["thoughts", "fear"] },
  { id: "epictetus-wish", teacher: "Epictetus", kind: "said", source: "Enchiridion VIII (Higginson, 1865)", text: "Demand not that events should happen as you wish; but wish them to happen as they do happen, and you will go on well.", look: "Notice one thing that isn't how you wanted it, and try wishing it exactly as it is. What happens inside?", themes: ["desire", "now"] },
  { id: "marcus-present", teacher: "Marcus Aurelius", kind: "said", source: "Meditations II.14 (Long, 1862)", text: "For the present is the only thing of which a man can be deprived…", look: "Try to find a moment other than this one that you actually have in your hands.", themes: ["now"] },
  { id: "marcus-retreat", teacher: "Marcus Aurelius", kind: "said", source: "Meditations IV.3 (Long, 1862)", text: "For nowhere either with more quiet or more freedom from trouble does a man retire than into his own soul…", look: "Take a holiday inside for three breaths. No trip needed.", themes: ["stillness", "self"] },
  { id: "marcus-opinion", teacher: "Marcus Aurelius", kind: "said", source: "Meditations IV.3 (Long, 1862)", text: "The universe is transformation: life is opinion.", look: "Spot one thing around you that's changing right now, and one opinion you're having about it.", themes: ["thoughts", "nature", "stories"] },
  { id: "marcus-judgement", teacher: "Marcus Aurelius", kind: "said", source: "Meditations VIII.47 (Long, 1862)", text: "If thou art pained by any external thing, it is not this thing that disturbs thee, but thy own judgement about it. And it is in thy power to wipe out this judgement now.", look: "Catch one grumpy judgement in your head and see if you can drop it, like letting go of a pebble.", themes: ["thoughts", "stories"] },
  { id: "seneca-imagination", teacher: "Seneca", kind: "said", source: "Letter 13 (Gummere, 1917)", text: "There are more things, Lucilius, likely to frighten us than there are to crush us; we suffer more often in imagination than in reality.", look: "Think of a worry. Is it happening right now, or only in your mind's movie?", themes: ["fear", "stories"] },
  { id: "pascal-room", teacher: "Blaise Pascal", kind: "said", source: "Pensées 139 (Trotter, 1910)", text: "I have discovered that all the unhappiness of men arises from one single fact, that they cannot stay quietly in their own chamber.", look: "Sit in your room for two minutes doing nothing at all. Watch what your mind tries to do instead.", themes: ["stillness", "desire"] },
  { id: "montaigne-dance", teacher: "Michel de Montaigne", kind: "said", source: "Essays III.13 (Cotton)", text: "When I dance, I dance; when I sleep, I sleep.", look: "Do the very next thing (drinking, walking, typing) as the only thing you're doing.", themes: ["now", "body", "play"] },
  { id: "julian-well", teacher: "Julian of Norwich", kind: "said", source: "Revelations of Divine Love 27 (Warrack, 1901)", text: "…all shall be well, and all shall be well, and all manner of thing shall be well.", look: "Say it slowly to yourself and notice what your shoulders do.", themes: ["fear", "love", "stillness"] },
  { id: "nietzsche-star", teacher: "Friedrich Nietzsche", kind: "said", source: "Thus Spake Zarathustra (Common, 1909)", text: "I tell you: one must still have chaos in one, to give birth to a dancing star.", look: "Notice the messiest feeling in you right now. What might it be getting ready to make?", themes: ["play", "thoughts"] },
  { id: "nietzsche-body", teacher: "Friedrich Nietzsche", kind: "said", source: "Thus Spake Zarathustra (Common, 1909)", text: "There is more sagacity in thy body than in thy best wisdom.", look: "Ask your body, not your head, what it needs right now. Then listen.", themes: ["body"] },
  { id: "james-attend", teacher: "William James", kind: "said", source: "The Principles of Psychology (1890)", text: "My experience is what I agree to attend to.", look: "Move your attention from these words to your feet. Did your whole world just change?", themes: ["thoughts", "now", "self"] },
  // Zen & Tao and the Buddha's way: verbatim, public domain
  { id: "laotzu-know-self", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 33 (Legge, 1891)", text: "He who knows other men is discerning; he who knows himself is intelligent.", look: "Name one thing you know about your best friend, then one thing you only just noticed about yourself. Which was harder?", themes: ["self"] },
  { id: "laotzu-overcome", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 33 (Legge, 1891)", text: "He who overcomes others is strong; he who overcomes himself is mighty.", look: "Next time you feel the itch to scroll or snack, wait three breaths first. Who won?", themes: ["self", "desire"] },
  { id: "laotzu-step", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 64 (Legge, 1891)", text: "…the journey of a thousand li commenced with a single step.", look: "Pick something huge you keep putting off and do the tiniest first step right now.", themes: ["now", "fear"] },
  { id: "laotzu-muddy", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 15 (Legge, 1891)", text: "Who can (make) the muddy water (clear)? Let it be still, and it will gradually become clear.", look: "When your head feels stirred up, sit for one minute without fixing anything. Does the mud settle by itself?", themes: ["stillness", "thoughts"] },
  { id: "laotzu-empty", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 11 (Legge, 1891)", text: "Clay is fashioned into vessels; but it is on their empty hollowness, that their use depends.", look: "Look at a cup, a room or the gap between two notes of music. Can you find the useful empty part?", themes: ["stillness", "nature"] },
  { id: "laotzu-water", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 8 (Legge, 1891)", text: "The highest excellence is like (that of) water.", look: "Pour a little water and watch where it goes. What would it be like to move through your day that way?", themes: ["nature"] },
  { id: "laotzu-content", teacher: "Lao Tzu", kind: "said", source: "Tao Te Ching 44 (Legge, 1891)", text: "Who is content / Needs fear no shame. / Who knows to stop / Incurs no blame.", look: "At your next snack, try to catch the exact moment \"enough\" arrives.", themes: ["desire", "body"] },
  { id: "chuangtzu-butterfly", teacher: "Chuang Tzu", kind: "said", source: "Chuang Tzŭ II (H. A. Giles, 1889)", text: "Once upon a time, I, Chuang Tzŭ, dreamt I was a butterfly… Now I do not know whether I was then a man dreaming I was a butterfly, or whether I am now a butterfly dreaming I am a man.", look: "Right now, how do you actually know you're awake? Try to find the proof.", themes: ["self", "play"] },
  { id: "chuangtzu-fishes", teacher: "Chuang Tzu", kind: "said", source: "Musings of a Chinese Mystic (L. Giles, 1906)", text: "\"You not being a fish yourself,\" said Hui Tzŭ, \"how can you possibly know in what consists the pleasure of fishes?\" \"And you not being I,\" retorted Chuang Tzŭ, \"how can you know that I do not know?\"", look: "Watch a bird, a pet or a person for a minute. What do you think they feel, and how do you know?", themes: ["play", "nature"] },
  { id: "chuangtzu-mirror", teacher: "Chuang Tzu", kind: "said", source: "Musings of a Chinese Mystic (L. Giles, 1906)", text: "When water is still, it is like a mirror, reflecting the beard and the eyebrows.", look: "Sit still for ten breaths. Does your mind get clearer, like a puddle when you stop splashing it?", themes: ["stillness", "thoughts"] },
  { id: "chuangtzu-dream", teacher: "Chuang Tzu", kind: "said", source: "Musings of a Chinese Mystic (L. Giles, 1906)", text: "While they dream, they do not know that they dream.", look: "Catch one daydream you were lost in today. When did you notice it was only a daydream?", themes: ["thoughts", "stories"] },
  { id: "chuangtzu-frog", teacher: "Chuang Tzu", kind: "said", source: "Musings of a Chinese Mystic (L. Giles, 1906)", text: "You cannot speak of ocean to a well-frog,—the creature of a narrower sphere.", look: "What's one \"well\" you might live in, an idea about yourself you've never peeked over the edge of?", themes: ["stories", "self"] },
  { id: "liehtzu-axe", teacher: "Lieh Tzu", kind: "said", source: "Taoist Teachings from Lieh Tzŭ (L. Giles, 1912)", text: "A man, having lost his axe, suspected his neighbour's son of having taken it. … The next day, when he saw his neighbour's son again, he found no trace of guilt in his movements, his actions, or his general demeanour.", look: "Think of someone you're annoyed with. How much of what you \"see\" in them is a story?", themes: ["stories", "thoughts"] },
  { id: "buddha-thought", teacher: "Buddha", kind: "said", source: "Dhammapada 1 (Müller, 1881)", text: "All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts.", look: "Notice the next thought that pops up. Did you choose it, or did it just arrive?", themes: ["thoughts", "self"] },
  { id: "buddha-tame", teacher: "Buddha", kind: "said", source: "Dhammapada 35 (Müller, 1881)", text: "It is good to tame the mind, which is difficult to hold in and flighty, rushing wherever it listeth; a tamed mind brings happiness.", look: "Count ten breaths without your mind running off. How far do you get before it bolts?", themes: ["thoughts", "stillness"] },
  { id: "buddha-bubble", teacher: "Diamond Sutra", kind: "said", source: "Diamond Sutra 32 (Müller, 1894)", text: "Stars, darkness, a lamp, a phantom, dew, a bubble. / A dream, a flash of lightning, and a cloud--thus we should look upon the world (all that was made).", look: "Pick any feeling you have right now and watch it like a soap bubble. Does it change or pop?", themes: ["now", "nature"] },
  // Sages of India: verbatim, public domain
  { id: "kabir-beside", teacher: "Kabir", kind: "said", source: "Songs of Kabir I (Tagore, 1915)", text: "O servant, where dost thou seek Me? / Lo! I am beside thee.", look: "Look up from this card and notice: where exactly are you looking from right now?", themes: ["self", "now"] },
  { id: "kabir-fish", teacher: "Kabir", kind: "said", source: "Songs of Kabir XLIII (Tagore, 1915)", text: "I laugh when I hear that the fish in the water is thirsty: / You do not see that the Real is in your home, and you wander from forest to forest listlessly!", look: "Is there something you keep searching for that might already be right here, like a fish looking for water?", themes: ["self", "desire"] },
  { id: "kabir-musk", teacher: "Kabir", kind: "said", source: "Songs of Kabir VI (Tagore, 1915)", text: "The musk is in the deer, but it seeks it not within itself: it wanders in quest of grass.", look: "Take one breath and check: is the good feeling you're chasing already somewhere inside you?", themes: ["desire", "self"] },
  { id: "tagore-stream", teacher: "Rabindranath Tagore", kind: "said", source: "Gitanjali 69 (1912)", text: "The same stream of life that runs through my veins night and day runs through the world and dances in rhythmic measures.", look: "Feel the pulse in your wrist, then look at a tree or a cloud. Is it the same dance?", themes: ["body", "nature", "love"] },
  { id: "tagore-seashore", teacher: "Rabindranath Tagore", kind: "said", source: "Gitanjali 60 (1912)", text: "On the seashore of endless worlds children meet. The infinite sky is motionless overhead and the restless water is boisterous.", look: "Can you be the still sky and the splashing water at once: calm above, playful below?", themes: ["play", "stillness", "nature"] },
  { id: "tagore-moments", teacher: "Rabindranath Tagore", kind: "said", source: "Stray Birds 59 (1916)", text: "Never be afraid of the moments--thus sings the voice of the everlasting.", look: "Is this exact moment actually scary, or only the story about the next one?", themes: ["fear", "now"] },
  { id: "tagore-flowers", teacher: "Rabindranath Tagore", kind: "said", source: "Stray Birds 102 (1916)", text: "Do not linger to gather flowers to keep them, but walk on, for flowers will keep themselves blooming all your way.", look: "Think of something lovely from today. Enjoy it, let it go, and see what turns up next.", themes: ["desire", "now"] },
  { id: "kena-eye", teacher: "Upanishads", kind: "said", source: "Kena Upanishad I.6 (Paramananda, 1919)", text: "That which is not seen by the eye, but by which the eye is able to see: know that alone to be the Brahman, not this which people worship here.", look: "Look at your hand, then try to look at the looking itself. Can you find it?", themes: ["self", "stillness"] },
  { id: "kena-mind", teacher: "Upanishads", kind: "said", source: "Kena Upanishad I.5 (Paramananda, 1919)", text: "That which cannot be thought by mind, but by which, they say, mind is able to think: know that alone to be the Brahman, not this which people worship here.", look: "Watch for the next thought. What was here just before it arrived?", themes: ["thoughts", "self"] },
  { id: "isha-all", teacher: "Upanishads", kind: "said", source: "Isha Upanishad 6 (Paramananda, 1919)", text: "He who sees all beings in the Self and the Self in all beings, he never turns away from It (the Self).", look: "Look at the next person or animal you see and wonder: what if they're a \"me\" too, from the inside?", themes: ["self", "love"] },
  { id: "chandogya-salt", teacher: "Upanishads", kind: "said", source: "Chandogya Upanishad VI.13 (Müller, 1879)", text: "Here also, in this body, forsooth, you do not perceive the True (Sat), my son; but there indeed it is. … It is the True. It is the Self, and thou, O Svetaketu, art it.", look: "Stir salt into water and taste it. You can't see it anywhere, yet it's everywhere. Like you?", themes: ["self", "body"] },
  { id: "gita-fruit", teacher: "Krishna", kind: "said", source: "Bhagavad Gita II (Arnold, 1885)", text: "Find full reward / Of doing right in right! Let right deeds be / Thy motive, not the fruit which comes from them.", look: "Do one small thing right now, like drawing a circle, just for the doing, not for how it turns out.", themes: ["desire", "play", "now"] },
  { id: "gita-lamp", teacher: "Krishna", kind: "said", source: "Bhagavad Gita VI (Arnold, 1885)", text: "Steadfast a lamp burns sheltered from the wind; / Such is the likeness of the Yogi's mind / Shut from sense-storms and burning bright to Heaven.", look: "Sit for three breaths and picture your attention as a candle flame. Can it stay steady while sounds blow past?", themes: ["stillness", "thoughts"] },
  { id: "patanjali-seer", teacher: "Patanjali", kind: "said", source: "Yoga Sutras II.20 (Johnston, 1912)", text: "The Seer is pure vision. Though pure, he looks out through the vesture of the mind.", look: "Your thoughts are like tinted glasses. Can you notice the glasses, not just what you see through them?", themes: ["self", "thoughts"] },
  { id: "ramakrishna-ego", teacher: "Ramakrishna", kind: "said", source: "Sayings 353 (Max Müller, 1898)", text: "What is my ego? Is it my hand, or foot, or flesh, or blood, or muscle, or tendon? Ponder deep, and thou shalt know that there is no such thing as I.", look: "Go on a hunt: point to your hand, your foot, your nose. Which one is the \"I\"?", themes: ["self", "body"] },
  { id: "ramakrishna-sea", teacher: "Ramakrishna", kind: "said", source: "Sayings 364 (Max Müller, 1898)", text: "God is seen when the mind is tranquil. When the mental sea is agitated by the wind of desires, it cannot reflect God, and then God-vision is impossible.", look: "Picture your mind as a pond. What happens to the reflection when a wish ripples across it?", themes: ["stillness", "desire"] },
  { id: "vivekananda-monkey", teacher: "Vivekananda", kind: "said", source: "Raja Yoga VI (1896)", text: "The first lesson, then, is to sit for some time and let the mind run on. The mind is bubbling up all the time. It is like that monkey jumping about. Let the monkey jump as much as he can; you simply wait and watch.", look: "Set a one-minute timer and just watch your monkey mind jump. No catching, only watching.", themes: ["thoughts", "play", "stillness"] },
];

export const wisdomById = (id: string | null | undefined) => WISDOM.find((w) => w.id === id) ?? null;

/** Same card all day, a different one tomorrow. */
export function wisdomOfDay(now = Date.now()) {
  const day = Math.floor(now / 86_400_000);
  return WISDOM[((day * 7919) % WISDOM.length + WISDOM.length) % WISDOM.length];
}

/** Quests on the path. The order is a suggestion; what's discovered on each one is the user's own. */
export interface Quest { id: string; title: string; tagline: string; wisdom: string; mission: string; ask: string }

export const QUESTS: Quest[] = [
  { id: "noise", title: "The Noisy Room", tagline: "Meet the voice in your head", wisdom: "tolle-watch", mission: "For two minutes, just listen to your thoughts like a radio. Don't change the station. Count how many thoughts show up.", ask: "What did the voice talk about most? And who was listening?" },
  { id: "riverbank", title: "The Riverbank", tagline: "You don't have to get on every boat", wisdom: "osho-witness", mission: "Sit somewhere comfy. Each time a thought floats by, quietly say \"boat\" and let it pass.", ask: "Was there any space between the boats? What was there?" },
  { id: "who", title: "The Big Question", tagline: "Who am I, really?", wisdom: "ramana-who", mission: "Ask yourself \"Who am I?\" three times, slowly. Don't answer with your name or your job. Just look.", ask: "What did you find when you looked, not thought?" },
  { id: "stories", title: "The Story Hunter", tagline: "Catch a story in the act", wisdom: "crone-without", mission: "Today, catch one sentence your mind says about you (\"I'm bad at…\", \"I always…\"). Write it down like a detective.", ask: "What's the story? Is it 100% true? Who would you be without it?" },
  { id: "arrow", title: "The Second Arrow", tagline: "Pain vs. the story about the pain", wisdom: "buddha-arrow", mission: "Next time something annoys or hurts you, pause and split it in two: what actually happened, and what your mind added.", ask: "What was the first arrow? What was the second one?" },
  { id: "body", title: "The Remote Control", tagline: "Your body knows how to calm down", wisdom: "science-breath", mission: "Breathe in for 4, out for 6, five times. Then feel your hands from the inside, without looking at them.", ask: "What changed in your body? In your thoughts?" },
  { id: "nature", title: "The Slow Teacher", tagline: "Let nature show you its pace", wisdom: "laotzu-nature", mission: "Go outside. Find a tree, the sky or some water, and watch it for five minutes without naming anything.", ask: "What did nature teach you that a book couldn't?" },
  { id: "now", title: "The Only Moment", tagline: "Is there a problem right now?", wisdom: "tolle-now", mission: "Three times today, stop and ask: \"Right now, this exact second, is anything actually wrong?\"", ask: "What did you notice each time you checked?" },
  { id: "compass", title: "The Excitement Compass", tagline: "Follow what lights you up", wisdom: "bashar-excitement", mission: "Do the most exciting small thing you can do today, and let go of how it turns out.", ask: "What did you do? How did it feel to not need it to go perfectly?" },
  { id: "love", title: "The Old Rule", tagline: "Love is stronger than a grudge", wisdom: "buddha-hatred", mission: "Think of someone who bugs you. Silently wish them one good thing, and mean it as much as you can.", ask: "What happened inside you when you did that?" },
  { id: "silence", title: "The Treasure Inside", tagline: "Find the quiet that's always there", wisdom: "jesus-within", mission: "Sit in silence for five minutes. Don't chase calm; just notice what's already quiet underneath the noise.", ask: "Was there something there that didn't change, even when thoughts did?" },
  { id: "your-own", title: "Your Own Path", tagline: "No one can walk it for you", wisdom: "krishnamurti-no-guru", mission: "Look back at everything you discovered on this path. Write the one thing you now know for yourself, in your own words.", ask: "What do you know now, not because someone said it, but because you saw it?" },
];

export const questById = (id: string) => QUESTS.find((q) => q.id === id) ?? null;
